server:
  port: 8080
  servlet:
    context-path: /v1/gray/
spring:
  profiles:
    active: local
    location: banner.txt
  application:
    name: schoolLife-service
mybatis:
  mapper-locations: classpath:mapping/*.xml