server:
  port: 8015
  servlet:
    context-path: /v1/gray/
spring:
  profiles:
    active: local
    location: banner.txt
  application:
    name: schoolLife-securityService
mybatis:
  mapper-locations: classpath:mapping/*.xml